#!/bin/sh
branch=$(git branch --show-current)

# # Prevent committing into master
# if [ "$branch" = "master" ]; then
#   echo "You can't commit directly to master branch"
#   exit 1
# fi

# Format staged files with eslint and prettier as a plugin
yarn run format:staged
